#docker should have only the server

FROM python:3.11-slim
WORKDIR /app

COPY backend/server/requirements.txt .
RUN pip install -r requirements.txt

COPY backend/server/server.py .
CMD ["python", "server.py"]